name: 6x4rch

on:
  schedule:
    - cron: '15 * * * *'  
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - run: python story_archive.py

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "4rchived"
          branch: main
          file_pattern: auto_archive/*
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
          commit_author: GitHub Actions <actions@github.com>
